retrieval_task:
  description: >
    Retrieve the most relevant documents or snippets from the internal knowledge base
    that could help answer the user's question: "{query}".
  expected_output: >
    A Pydantic SearchResults object, containing a 'results' field which is a list
    of SearchResult objects. Each SearchResult must include 'content', 'similarity',
    and 'metadata' fields.
  agent: information_retriever

answer_generation_task:
  description: |
    You will receive a Pydantic SearchResults object with a single 'results' key from the `retrieval_task`.
    Its value is a **list of search result dictionaries**, each result dictionary contains:
    - **content**: (string) Relevant text excerpt.
    - **similarity**: (float) Relevance score.
    - **metadata**: (dictionary) Includes 'file_name', 'page_label', and 'pk'.

    **IMPORTANT - Content Filtering:**
    The content field contains document metadata that you MUST filter out:
    - Date/time stamps
    - Document headers and footers
    - Administrative metadata and navigation elements

    **Your primary goal is to extract ONLY the substantive information that directly answers the user's question - {query}.**

    **Conditional Output Rules:**
    1. **If the 'results' list in the SearchResults object is empty:**
       Your final output MUST be **EXACTLY** this text: "No relevant information found in the knowledge base."
       Do NOT add any other text, formatting, or explanation.

    2. **If the 'results' list in the SearchResults object has items:**
       You MUST create a well-formatted answer based on the filtered content.
       - Use **bold text**, bullet points, and clear formatting to enhance readability.
       - Include a "Sources" section at the end, grouping citations by document.
       - Citations should be formatted as: "Document.pdf (pp. x, y, z)".
       - Ensure your answer contains **no timestamps or headers** from the original content.

  expected_output: |
    # **Example for when results ARE found:**

    **This is an example of a well-formatted answer.** It uses bold text for emphasis and bullet points for lists:
    * Item one from the relevant information.
    * Item two, which directly answers the query.
    * Any other key details extracted from the content.

    <details>
    <summary>Sources</summary>
    Find more information in: DocumentA.pdf (pp. 1, 2), DocumentB.pdf (pp. 5, 6, 7)
    </details>

    # **Example for when NO results are found:**

    No relevant information found in the knowledge base.

  agent: answer_generator