retrieval_task:
  description: >
    Retrieve the most relevant documents or snippets from the internal knowledge base
    that could help answer the user's question: "{query}".
  expected_output: >
    A list of the most relevant text excerpts or document references from the knowledge base.
  agent: information_retriever

answer_generation_task:
  description: |
    You will receive a list of SearchResult objects from the `retrieval_task`. Each SearchResult object contains:
    - content: str (relevant text excerpt)
    - similarity: float (relevance score)
    - metadata: dict (file_name, page_label, pk)

    **IMPORTANT - Content Filtering:**
    The content field contains document metadata that you MUST filter out:
    - Date/time stamps
    - Document headers and footers
    - Administrative metadata and navigation elements
    
    **Extract ONLY the substantive information** that directly answers the user's question - {query}.

    **Your task:**
    1. **If the SearchResult list is empty** → Return EXACTLY: "No relevant information found in the knowledge base." (Nothing else)
    2. **If SearchResult list has items** → Create structured answer + add sources section
    3. Use **bold text**, bullet points, and clear formatting
    4. Group citations by document: "Document.pdf (pp. x, y, z)"

  expected_output: |
    **When SearchResult list is NOT empty, format as:**

    [Your well-formatted answer with filtered content - no timestamps/headers]

    <details>
    <summary>Sources</summary>
    Find more information in: [Document Name] (pp. x, y, z)
    </details>

    **When SearchResult list IS empty, output EXACTLY this text with no additional formatting:**

    No relevant information found in the knowledge base.

  agent: answer_generator