from src.flexr.crews.reception_crew.reception_crew import ReceptionCrew
from src.flexr.crews.sales_crew.sales_crew import SalesCrew
from src.flexr.crews.after_sales_crew.after_sales_crew import AfterSalesCrew
from src.flexr.crews.file_crew.file_crew import FileCrew
from src.flexr.crews.qa_crew.qa_crew import QACrew
from src.flexr.crews.img_crew.img_crew import ImgCrew
from src.flexr.utils.common import get_crew_metadata


def execute_crew(crew_name: str, input_data: dict):
    if crew_name == "reception":
        crew = ReceptionCrew().crew()
    elif crew_name == "sales":
        crew = SalesCrew().crew()
    elif crew_name == "qa":
        crew = QACrew().crew()
    elif crew_name == "img":
        crew = ImgCrew().crew()
    elif crew_name == "aftersales":
        crew = AfterSalesCrew().crew()
    elif crew_name == "file":
        crew = FileCrew().crew()
    else:
        raise ValueError(f"Invalid crew name: {crew_name}")

    metadata = get_crew_metadata(crew)
    result = crew.kickoff(input_data)
    """
    id: generated by UUID, used to trace the specific conversation
    key: MD5 hash of agents and tasks, used to trace the same crew
    """
    return {"id": crew.id, "metadata":metadata, **result.model_dump()} 
